-- MySQL Script generated by MySQL Workbench
-- 10/14/16 03:42:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ebayDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ebayDB` ;

-- -----------------------------------------------------
-- Schema ebayDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ebayDB` DEFAULT CHARACTER SET utf8 ;
USE `ebayDB` ;

-- -----------------------------------------------------
-- Table `ebayDB`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebayDB`.`Users` ;

CREATE TABLE IF NOT EXISTS `ebayDB`.`Users` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NOT NULL,
  `Password` CHAR(32) NOT NULL,
  `FirstName` VARCHAR(20) NOT NULL,
  `LastName` VARCHAR(20) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebayDB`.`advertisements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebayDB`.`advertisements` ;

CREATE TABLE IF NOT EXISTS `ebayDB`.`advertisements` (
  `adID` INT Not NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `detail` VARCHAR(240) NULL,
  `price` INT NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `sellerID` INT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`adID`),
    FOREIGN KEY (`sellerID`)
    REFERENCES `ebayDB`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebayDB`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebayDB`.`transactions` ;

CREATE TABLE IF NOT EXISTS `ebayDB`.`transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sellerID` INT NOT NULL,
  `buyerID` INT NOT NULL,
  `ItemID` INT NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`sellerID`)
    REFERENCES `ebayDB`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`buyerID`)
    REFERENCES `ebayDB`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`ItemID`)
    REFERENCES `ebayDB`.`advertisements` (`adID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
